#!/usr/bin/env python
# -*- coding: utf8 -*-


import os
import sys
import time
import optparse


def main(argv):

    bgral = 0.0
    flag = '-append '

    parser = optparse.OptionParser(
             usage='Usage: %prog [options] infiles outfile',
             version=' %prog Version 0.5.0 by David Hernandez <davidhdz> 2021')

    parser.add_option('-v', '--vertical', help='vertical arrangement (default)',
                      dest='orientacion', default='True', action='store_true')
    parser.add_option('-z', '--horizontal', help='horizontal arrangement',
                      dest='orientacion', action='store_false')
    parser.add_option('-g', '--gap', help='gap size between images, default 0',
                      dest='tamano', type='float', default=0, metavar='number')
    parser.add_option('-b', '--bgcolor', help='background color, default white',
                      dest='fondo', default='white', metavar='color')

    (opts, args) = parser.parse_args()

    if opts.orientacion is True:
        flag = '-append '
    elif opts.orientacion is False:
        flag = '+append '
    if opts.tamano:
        bgral = opts.tamano / 2
        flag = flag + '-border ' + str(opts.tamano) + ' '
    if opts.fondo:
        flag = flag + '-bordercolor ' + opts.fondo + ' '
    if len(args) < 2:
        parser.print_help()
        sys.exit()

    timeinit = time.strftime("%Y%m%d%H%M%S")
    tempfile = timeinit + '_catimg.tmp'
    target = args[-1]
    outfile = 'catimage_' + timeinit + "_" + target
    source = '"' + '" "'.join(args[:-1]) + '"'
    if os.path.exists(target):
            print('{} exists' .format(target))
            target = outfile
    os.system('convert -gravity Center ' + flag + ' ' + source + ' ' + tempfile)
    os.system('convert -border ' + str(bgral) + ' -bordercolor ' + opts.fondo + ' ' + tempfile + ' ' + target)
    os.remove(tempfile)
    print(('Image generated as ' + target))


if __name__ == '__main__':
    main(sys.argv)
