#!/usr/bin/env python
# -*- coding: utf8 -*-


import os
import sys
import time
import optparse


def main(argv):

    bgral = 0.0
    flag = '-append '

    parser = optparse.OptionParser(
             usage='Usage: %prog [options] infiles outfile',
             version=' %prog Version 0.1.0 by David Hernandez <davidhdz> 2014')

    parser.add_option('-v', '--vertical', help='vertical arrangement (default)',
                      dest='orienteacion', default='True', action='store_true')
    parser.add_option('-z', '--horizontal', help='horizontal arrangement',
                      dest='orientacion', action='store_false')
    parser.add_option('-s', '--size', help='size between images, default 0',
                      dest='tamano', type='float', default=0, metavar='number')
    parser.add_option('-b', '--bgcolor', help='background color, default white',
                      dest='fondo', default='white', metavar='color')

    (opts, args) = parser.parse_args()

    if opts.orientacion is True:
        flag = '-append '
    elif opts.orientacion is False:
        flag = '+append '
    if opts.tamano:
        bgral = opts.tamano / 2
        flag = flag + '-border ' + str(opts.tamano) + ' '
    if opts.fondo:
        flag = flag + '-bordercolor ' + opts.fondo + ' '
    if len(args) < 2:
        parser.print_help()
        sys.exit()

    tempfile = (time.strftime("%Y%m%d%H%M%S") + '_catimg.tmp')
    source = '"' + '" "'.join(args[:-1]) + '"'
    target = args[-1]
    print source
    os.system('convert ' + flag + source + ' ' + tempfile)
    os.system('convert -border ' + str(bgral) + ' -bordercolor ' + opts.fondo + 
        ' ' + tempfile + ' ' + target)
    os.remove(tempfile)
    print(('Image generated as ' + target))


if __name__ == '__main__':
    main(sys.argv)
